
name: 'Setup Docker Buildx Cache'
description: 'Sets up Docker Buildx with caching'

runs:
  using: "composite"
  steps:
    - name: Configure buildx
      uses: docker/setup-buildx-action@v2
      with:
        cleanup: false
        version: latest
        config-inline: |
          [registry."ghcr.io"]
            mirrors = ["192.168.128.1:5001"]

          [registry."docker.io"]
            mirrors = ["192.168.128.1:5000"]

          [registry."192.168.128.1:5000"]
            http = true
            insecure = true

          [registry."192.168.128.1:5001"]
            http = true
            insecure = true

    - name: Set the NPM registry if it is set
      shell: bash
      run: |
        if [[ -n "${NPM_CONFIG_REGISTRY}" ]]; then
          pnpm config set registry $NPM_CONFIG_REGISTRY
        fi
